# Generated by Django 5.2.8 on 2025-11-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_store_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='type',
            new_name='shoe_type',
        ),
        migrations.RenameField(
            model_name='shoetype',
            old_name='type',
            new_name='shoe_type',
        ),
    ]
