# Generated by Django 5.2.8 on 2025-11-13 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_store_api', '0002_rename_type_shoe_shoe_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoetype',
            name='atribute',
        ),
        migrations.AddField(
            model_name='shoetype',
            name='atribute',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='shoes_store_api.attribute'),
            preserve_default=False,
        ),
    ]
