# Generated by Django 5.2.8 on 2025-11-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_store_api', '0003_remove_shoetype_atribute_shoetype_atribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoetype',
            old_name='shoe_type',
            new_name='name',
        ),
    ]
