# Generated by Django 5.2.8 on 2025-11-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_store_api', '0004_rename_shoe_type_shoetype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoetype',
            old_name='atribute',
            new_name='attribute',
        ),
    ]
