# Generated by Django 5.2.8 on 2025-11-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_store_api', '0005_rename_atribute_shoetype_attribute'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attribute',
            new_name='Attributes',
        ),
        migrations.RenameField(
            model_name='shoetype',
            old_name='attribute',
            new_name='attributes',
        ),
    ]
