# Generated by Django 5.2.8 on 2025-11-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_store_api', '0006_rename_attribute_attributes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributes',
            old_name='color',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='attributes',
            old_name='gender',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='material',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='size',
        ),
    ]
