# Generated by Django 5.2.8 on 2025-11-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_store_api', '0007_rename_color_attributes_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoetype',
            name='attributes',
        ),
        migrations.AddField(
            model_name='shoetype',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='shoes_store_api.attributes'),
        ),
    ]
